version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore local plugin files that Dependabot can't handle
      - dependency-name: "neograf-plugin"
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]