north:
  restart: unless-stopped
  image: ghcr.io/fairmat-nfdi/nomad-distro-template/jupyter:main  # Official working image
  container_name: nomad_oasis_north
  environment:
    NOMAD_SERVICE: nomad_oasis_north
    NOMAD_NORTH_DOCKER_NETWORK: nomad_oasis_network
    NOMAD_NORTH_HUB_CONNECT_IP: north
    NOMAD_NORTH_HUB_IP: "0.0.0.0"
    NOMAD_NORTH_HUB_HOST: north
    NOMAD_SERVICES_API_HOST: app
    NOMAD_FS_EXTERNAL_WORKING_DIRECTORY: /volume1/docker/neograf-data-oasis
    NOMAD_RABBITMQ_HOST: rabbitmq
    NOMAD_ELASTIC_HOST: elastic
    NOMAD_MONGO_HOST: mongo
  depends_on:
    app:
      condition: service_healthy
  volumes:
    - /volume1/docker/neograf-data-oasis/configs/nomad.yaml:/app/nomad.yaml
    - /volume1/docker/neograf-data-oasis/.volumes/fs:/app/.volumes/fs
    - /var/run/docker.sock:/var/run/docker.sock
  user: '1000:121'
  command: python -m nomad.cli admin run hub  # Keep original command
  healthcheck:
    test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8081/nomad-oasis/north/hub/health"]
    interval: 10s
    timeout: 10s
    retries: 30
    start_period: 10s