services:
  api_host: "localhost"
  api_base_path: "/nomad-oasis"

oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    options:
      jupyter:
        image: ghcr.io/fairmat-nfdi/nomad-distro-template/jupyter:main

meta:
  deployment: "neograf-oasis"
  deployment_url: "http://10.0.0.21:8000"
  maintainer_email: "jswanson@neograf.com"
  title: NeoGraf Materials Data Hub
  description: Advanced Materials Research Data Management Platform
  footer: © NeoGraf Solutions, 2025

logstash:
  enabled: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1

plugins:
  include:
    # Your custom NeoGraf plugin
    - "neograf_plugin"
    
    # Keep any existing plugins listed here
    # The template will automatically load all plugins from pyproject.toml
    # but explicitly including yours ensures it's definitely loaded
